config/routes.rb
Rails.application.routes.draw do

  # Admin Resources
  namespace :admin do
    resources :tutorials, :technologies
  end

  resources :tutorials, only: [:index, :show]

  devise_for :users, controllers: {
  	omniauth_callbacks: 'users/omniauth_callbacks',
  	registrations: 'users/registrations'
  }

  get 'home/index'

  get 'home/private'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :technologies

  validates :title, :body, :slug, :published, :technology_ids, presence: true
end

app/controllers/admin/tutorials_controller.rb
class Admin::TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.includes(:user).order('tutorials.created_at DESC').all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = current_user.tutorials.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to [:admin, @tutorial], notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to [:admin, @tutorial], notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to admin_tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorial_params
      p = params.require(:tutorial).permit(:title, :body, :slug, :published, :technology_ids => [])
      p[:technology_ids] = Technology.where(id: p[:technology_ids]).pluck(:id)
      p
    end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.includes(:user).all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end
end

app/views/admin/tutorials/_form.html.erb
<%= form_with model: [:admin, tutorial], local: true do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :tutorial_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :tutorial_body %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :tutorial_slug %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.number_field :published, id: :tutorial_published %>
  </div>

  <div class="field">
    <%= form.label :technology_ids %>
    <%= form.select :technology_ids, Technology.pluck(:title, :id), {}, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/tutorials/edit.html.erb
<h1>Editing Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Show', [:admin, @tutorial] %> |
<%= link_to 'Back', admin_tutorials_path %>

app/views/admin/tutorials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tutorials</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Slug</th>
      <th>Published</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= tutorial.title %></td>
        <td><%= tutorial.body %></td>
        <td><%= tutorial.slug %></td>
        <td><%= tutorial.published %></td>
        <td><%= tutorial.user %></td>
        <td><%= link_to 'Show', [:admin, tutorial] %></td>
        <td><%= link_to 'Edit', edit_admin_tutorial_path(tutorial) %></td>
        <td><%= link_to 'Destroy', [:admin, tutorial], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutorial', new_admin_tutorial_path %>

app/views/admin/tutorials/new.html.erb
<h1>New Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Back', admin_tutorials_path %>

app/views/admin/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tutorial.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tutorial.body %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @tutorial.slug %>
</p>

<p>
  <strong>Published:</strong>
  <%= @tutorial.published %>
</p>

<p>
  <strong>User:</strong>
  <%= @tutorial.user %>
</p>

<%= link_to 'Edit', edit_admin_tutorial_path(@tutorial) %> |
<%= link_to 'Back', admin_tutorials_path %>