config/routes.rb
Rails.application.routes.draw do

  # Admin Resources
  namespace :admin do
    resources :tutorials, :technologies
  end

  resources :tutorials, only: [:index, :show]

  devise_for :users, controllers: {
  	omniauth_callbacks: 'users/omniauth_callbacks',
  	registrations: 'users/registrations'
  }

  get 'home/index'

  get 'home/private'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/technology.rb
class Technology < ApplicationRecord
	has_and_belongs_to_many :tutorials

	validates :title, :slug, :body, presence: true
end

app/controllers/admin/technologies_controller.rb
class Admin::TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to [:admin, @technology], notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to [:admin, @technology], notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to admin_technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:title, :slug, :body)
    end
end

app/views/admin/technologies/_form.html.erb
<%= form_with(model: [:admin, technology], local: true) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :technology_title %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :technology_slug %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :technology_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Show', [:admin, @technology] %> |
<%= link_to 'Back', admin_technologies_path %>

app/views/admin/technologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Technologies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.title %></td>
        <td><%= technology.slug %></td>
        <td><%= technology.body %></td>
        <td><%= link_to 'Show', [:admin, technology] %></td>
        <td><%= link_to 'Edit', edit_admin_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', [:admin, technology], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technology', new_admin_technology_path %>

app/views/admin/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Back', admin_technologies_path %>

app/views/admin/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @technology.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @technology.slug %>
</p>

<p>
  <strong>Body:</strong>
  <%= @technology.body %>
</p>

<%= link_to 'Edit', edit_admin_technology_path(@technology) %> |
<%= link_to 'Back', admin_technologies_path %>