config/routes.rb
Rails.application.routes.draw do

  # Admin Resources
  namespace :admin do
    resources :tutorials, :technologies
  end

  resources :tutorials, only: [:index, :show]

  devise_for :users, controllers: {
  	omniauth_callbacks: 'users/omniauth_callbacks',
  	registrations: 'users/registrations'
  }

  get 'home/index'

  get 'home/private'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :technologies

  validates :title, :body, :slug, :published, :technology_ids, presence: true
end

app/controllers/admin/tutorials_controller.rb
class Admin::TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.includes(:user).order('tutorials.created_at DESC').all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = current_user.tutorials.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to [:admin, @tutorial], notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to [:admin, @tutorial], notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to admin_tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorial_params
      p = params.require(:tutorial).permit(:title, :body, :slug, :published, :technology_ids => [])
      p[:technology_ids] = Technology.where(id: p[:technology_ids]).pluck(:id)
      p
    end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.includes(:user).all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end
end

app/views/tutorials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tutorials</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Slug</th>
      <th>User</th>
      <th>Published</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= tutorial.title %></td>
        <td><%= tutorial.body %></td>
        <td><%= tutorial.slug %></td>
        <td><%= tutorial.user.username %></td>
        <td><%= tutorial.published %></td>
        <td><%= link_to 'Show', tutorial %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tutorial.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tutorial.body %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @tutorial.slug %>
</p>

<p>
  <strong>User:</strong>
  <%= @tutorial.user %>
</p>

<p>
  <strong>Published:</strong>
  <%= @tutorial.published %>
</p>

<%= link_to 'Back', tutorials_path %>